# Keep libjpeg-turbo's internal ABI separate from Qt's bundled libjpeg.
# Both libraries can be linked statically even when their public ABI versions match.
file(GLOB sources "${SOURCE_DIR}/src/*.h" "${SOURCE_DIR}/src/*.c")
list(REMOVE_ITEM sources "${SOURCE_DIR}/src/iv_jpeg_symbols.h")
set(symbols)
foreach(path IN LISTS sources)
    file(READ "${path}" contents)
    string(REGEX MATCHALL "(EXTERN|GLOBAL)\\([^)]*\\)[ \t\r\n]+[a-zA-Z_][a-zA-Z_0-9]*" declarations "${contents}")
    foreach(declaration IN LISTS declarations)
        string(REGEX REPLACE ".*\\)[ \t\r\n]+" "" symbol "${declaration}")
        if(symbol MATCHES "^j" AND NOT symbol MATCHES "^jsimd")
            list(APPEND symbols "${symbol}")
        endif()
    endforeach()
    # Include data tables and declarations that do not use EXTERN/GLOBAL.
    string(REGEX MATCHALL "jpeg[0-9]*_[a-zA-Z_0-9]+" jpeg_names "${contents}")
    list(APPEND symbols ${jpeg_names})
endforeach()
list(REMOVE_DUPLICATES symbols)
# These are convenience macros, not linker symbols.
list(REMOVE_ITEM symbols jpeg_common_fields jpeg_create_compress jpeg_create_decompress)
list(SORT symbols)
set(prefix_header "/* Generated private libjpeg symbol namespace. */\n")
foreach(symbol IN LISTS symbols)
    string(APPEND prefix_header "#define ${symbol} iv_turbo_${symbol}\n")
endforeach()
file(WRITE "${SOURCE_DIR}/src/iv_jpeg_symbols.h" "${prefix_header}")
# All codec sources use jinclude.h except the generated bit-count table.
foreach(name IN ITEMS jinclude.h jpeg_nbits.c)
    set(path "${SOURCE_DIR}/src/${name}")
    file(READ "${path}" contents)
    if(NOT contents MATCHES "iv_jpeg_symbols.h")
        file(WRITE "${path}" "#include \"iv_jpeg_symbols.h\"\n${contents}")
    endif()
endforeach()
# x86 SIMD provides this table in assembly instead of jpeg_nbits.c.
file(GLOB_RECURSE assembly "${SOURCE_DIR}/simd/*.asm" "${SOURCE_DIR}/simd/*.inc")
foreach(path IN LISTS assembly)
    file(READ "${path}" contents)
    string(REGEX REPLACE "(^|[^a-zA-Z_0-9])jpeg_nbits_table" "\\1iv_turbo_jpeg_nbits_table" patched "${contents}")
    if(NOT patched STREQUAL contents)
        file(WRITE "${path}" "${patched}")
    endif()
endforeach()
