name: Linux
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/linux.yml'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/linux.yml'
jobs:
  build-linux:
    name: Ubuntu
    runs-on: ubuntu-18.04
    env:
      QT_VER: "6.1.2"
      MANUAL_CACHING: "1"
      AUTO_CACHING: "true"
    steps:
      - name: Get repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common -y && \
          sudo add-apt-repository ppa:git-core/ppa -y && \
          sudo apt-get update && \
          sudo apt-get install git libexif-dev liblzma-dev libz-dev libssl-dev \
          libgtk2.0-dev libice-dev libsm-dev libicu-dev libdrm-dev dh-autoreconf \
          autoconf automake build-essential libxml2-dev libass-dev libfreetype6-dev \
          libgpac-dev libsdl1.2-dev libtheora-dev libtool libva-dev libvdpau-dev \
          libvorbis-dev libxcb1-dev libxcb-image0-dev libxcb-shm0-dev \
          libxcb-xfixes0-dev libxcb-keysyms1-dev libxcb-icccm4-dev libatspi2.0-dev \
          libxcb-render-util0-dev libxcb-util0-dev libxcb-xkb-dev libxrender-dev \
          libasound-dev libpulse-dev libxcb-sync0-dev libxcb-randr0-dev libegl1-mesa-dev \
          libx11-xcb-dev libxkbcommon-x11-dev libffi-dev libncurses5-dev pkg-config texi2html bison yasm \
          libwebp-dev zlib1g-dev xutils-dev chrpath gperf wget -y --force-yes && \
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
          sudo apt-get update && \
          sudo apt-get install gcc-11 g++-11 -y && \
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 && \
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 60 && \
          sudo update-alternatives --config gcc && \
          sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test -y && \
          sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main" -y && \
          sudo apt-get update && \
          sudo apt-get install libjasper-dev && \
          sudo add-apt-repository --remove "deb http://security.ubuntu.com/ubuntu xenial-security main" -y \

      - name: Set up environment variables
        run: |
          mkdir -p Libraries && cd Libraries
          echo "LibrariesPath=`pwd`" >> $GITHUB_ENV

      - name: libjpeg-turbo
        run: |
          cd $LibrariesPath
          git clone -b 2.1.0 --depth=1 https://github.com/libjpeg-turbo/libjpeg-turbo.git
          cd libjpeg-turbo
          cmake -S . -B build -DWITH_JPEG8=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          cd build
          make -j$(nproc)
          sudo make install

      - name: Clone
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: Generate cache key
        run: |
          gcc --version > CACHE_KEY.txt
          echo $MANUAL_CACHING >> CACHE_KEY.txt
          if [ "$AUTO_CACHING" == "true" ]; then
            thisFile=$REPO_NAME/.github/workflows/linux.yml
            echo `md5sum $thisFile | cut -c -32` >> CACHE_KEY.txt
          fi
          md5cache=$(md5sum CACHE_KEY.txt | cut -c -32)
          echo "CACHE_KEY=$md5cache" >> $GITHUB_ENV

      - name: Qt cache
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{ env.LibrariesPath }}/Qt-${{ env.QT_VER }}
          key: ${{ runner.OS }}-qt-${{ env.CACHE_KEY }}

      - name: Qt configure
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          cd $LibrariesPath

          git clone -b v$QT_VER --depth=1 git://code.qt.io/qt/qt5.git qt_src
          cd qt_src
          perl init-repository --module-subset=qtbase,qtimageformats
          git submodule update qtbase qtimageformats

          ./configure \
          -prefix "$LibrariesPath/Qt-$QT_VER" \
          -release \
          -opensource \
          -confirm-license \
          -qt-zlib \
          -qt-libpng \
          -qt-harfbuzz \
          -qt-pcre \
          -no-icu \
          -no-gtk \
          -no-zstd \
          -static \
          -static-runtime \
          -optimize-size \
          -dbus-runtime \
          -no-openssl \
          -no-opengl \
          -nomake examples \
          -nomake tests

      - name: Qt build
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: |
          cd $LibrariesPath/qt_src
          make -j$(nproc)
          make install

      - name: Image-viewer build
        run: |
          cd $REPO_NAME

          cmake -S . -B . -DCMAKE_PREFIX_PATH=$LibrariesPath/Qt-$QT_VER -DCMAKE_CXX_FLAGS="-s -static-libgcc -static-libstdc++"
          make -j$(nproc)

      - uses: actions/upload-artifact@master
        name: Upload artifact
        with:
          name: imageviewer-linux
          path: ${{ env.REPO_NAME }}/imageviewer
